### ISSUE TITLE
[Win/Mac] can't reuse port on Windows/Mac platforms

### ISSUE THREAD

**Issue by rainliu** [webrtc-rs/mdns#10]
Examples mdns_server.rs and mdns_query.rs can't run on the same machine for WIndows/Mac platform

**Comment by chertov** [comment]
i have the same problem on old linux openwrt platform
https://github.com/webrtc-rs/mdns/blob/main/src/conn/mod.rs#L60
fix line with only log output and it works
```rust
        #[cfg(target_family = "unix")] {
            if let Err(err) = socket.set_reuse_port(true) {
                log::error!("set_reuse_port err: {:?}", err);
            };
        }
```
```
2021-05-12 19:22:15,636 ERROR [webrtc_mdns::conn] set_reuse_port err: Os { code: 92, kind: Other, message: "Protocol not available" }
```

**Comment by metaclips** [comment]
@chertov are you using the latest version of openwrt?

**Comment by chertov** [comment]
@metaclips no, it is a very old custom openwrt build with 3.4.35 kernel on Hisilicon IP cameras from http://OpenIPC.org project
there are many reasons why it doesn't work.. kernel has chinese patch, i am using armv5te-unknown-linux-gnueabi rust target with uclibc.. but it works somehow!)
future openIPC releases will have a modern kernel with musl libc and many problems will go away

Today with a new __reuse_port__ cargo feature mDNS works from repo without modification!
Only Vnet AtomicU64 from [util](https://github.com/webrtc-rs/util) package doesn't work.. for now i am replacing them to AtomicU32
will try to add PR https://github.com/webrtc-rs/util/issues/6

**Comment by metaclips** [comment]
Nice. I do hope in the future we get to remove the `util` crate dependency from mDNS.

**Comment by chertov** [comment]
@metaclips what do you think should be used instead util-ifaces?
I tried to use https://docs.rs/pnet It is working, but the compilation process has become longer
https://github.com/chertov/webrtc-rs-mdns/tree/using-pnet-instead-util-ifaces

**Comment by rainliu** [comment]
If there are no additional features provided by pnet or something to be fixed, then I think we should stick to util-ifaces.
