### ISSUE TITLE
Make `set_reuse_port` optional on unix

### ISSUE THREAD

**Issue by metaclips** [webrtc-rs/mdns#15]
Make `set_reuse_port` an optional feature for Unix systems that don't support it.

**Comment by metaclips** [comment]
@chertov do you mind taking this up for a fix on Openwrt platforms?

**Comment by chertov** [comment]
@metaclips yes! thanks! i can to add an option for this to Config struct https://github.com/webrtc-rs/mdns/blob/main/src/conn/mod.rs#L52
Would this be a good solution?

**Comment by metaclips** [comment]
This would be a breaking change. Can we use [Cargo feature](https://doc.rust-lang.org/cargo/reference/features.html#features) with [conditional compilation](http://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/book/first-edition/conditional-compilation.html).
`reuse_port` should be a non-default feature and users have to enable it to use it `on Unix`.

**Comment by chertov** [comment]
Should i change ```reuse_port``` to ```disable_reuse_port```?
Tests in my PR are failed

**Comment by metaclips** [comment]
We can still use `reuse_port`, we can instead make `reuse_port` a default feature since our CI architecture requires it.

```rust
default = ["reuse_port"]
reuse_port = []
```
Users can then decide to [disable default feature](https://doc.rust-lang.org/cargo/reference/features.html#dependency-features)
