### ISSUE TITLE
Interop failed between webrtc-rs/mdns and pion/mdns

### ISSUE THREAD

**Issue by rainliu** [webrtc-rs/mdns#6]
Make interop between
webrtc-rs/mdns_server and pion/mdns_client
or
webrtc-rs/mdns_client and pion/mdns_server

but, right now inteop failed. 

cc @metaclips, @Sean-Der

**Comment by metaclips** [comment]
@rainliu it does work for me at my end running both client(pion) and server(webrtc-rs) also server(pion) and client(webrtc-rs) are you sure you're querying same local name?

**Comment by rainliu** [comment]
Let me double check.

**Comment by rainliu** [comment]
yes, it is false alarm. Both client/server interop works fine with pion's server/client.
