### ISSUE TITLE
fix windows build issue

### ISSUE THREAD

**Issue by rainliu** [webrtc-rs/mdns#8]
error[E0599]: no method named `set_reuse_port` found for struct `Socket` in the current scope
  --> src\conn\mod.rs:58:16
   |
58 |         socket.set_reuse_port(true)?;
   |                ^^^^^^^^^^^^^^ method not found in `Socket`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `webrtc-mdns`

Caused by:
  process didn't exit successfully: `rustc --crate-name webrtc_mdns --edition=2018 src\lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=94a72b67989749bb -C extra-filename=-94a72b67989749bb --out-dir D:\a\mdns\mdns\target\debug\deps -C incremental=D:\a\mdns\mdns\target\debug\incremental -L dependency=D:\a\mdns\mdns\target\debug\deps --extern ifaces=D:\a\mdns\mdns\target\debug\deps\libifaces-15719dda2bce5e12.rmeta --extern lazy_static=D:\a\mdns\mdns\target\debug\deps\liblazy_static-d20113d2098b0e23.rmeta --extern log=D:\a\mdns\mdns\target\debug\deps\liblog-63efc7b73bb752d4.rmeta --extern socket2=D:\a\mdns\mdns\target\debug\deps\libsocket2-f4645b2d6439cdd0.rmeta --extern tokio=D:\a\mdns\mdns\target\debug\deps\libtokio-e7256f96dbd0a9e5.rmeta --extern util=D:\a\mdns\mdns\target\debug\deps\libwebrtc_util-3e9881975ae8681c.rmeta -L native=D:\a\mdns\mdns\target\debug\build\ring-c9ff80a21dc4b97d\out` (exit code: 1)
Error: Process completed with exit code 1.

**Comment by urknall** [comment]
Hi, did you ever solve that problem?

Having something similar when building libmdns on illumos:

 Compiling libmdns v0.6.1 (/root/libmdns)
error[E0599]: no method named `set_reuse_port` found for struct `Socket` in the current scope
  --> src/address_family.rs:31:16
   |
31 |         socket.set_reuse_port(true)?;
   |                ^^^^^^^^^^^^^^ method not found in `Socket`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `libmdns`

To learn more, run the command again with --verbose.

**Comment by metaclips** [comment]
> Hi, did you ever solve that problem?
> 
> 
> 
> Having something similar when building libmdns on illumos:
> 
> 
> 
>  Compiling libmdns v0.6.1 (/root/libmdns)
> 
> error[E0599]: no method named `set_reuse_port` found for struct `Socket` in the current scope
> 
>   --> src/address_family.rs:31:16
> 
>    |
> 
> 31 |         socket.set_reuse_port(true)?;
> 
>    |                ^^^^^^^^^^^^^^ method not found in `Socket`
> 
> 
> 
> error: aborting due to previous error
> 
> 
> 
> For more information about this error, try `rustc --explain E0599`.
> 
> error: could not compile `libmdns`
> 
> 
> 
> To learn more, run the command again with --verbose.
> 
> 

Are you getting this error using this library?

**Comment by urknall** [comment]
i am getting a simliar error when building libmdns but not with this library,
the error appears also if you were only building libmdns on illumos...

i was just curious if rainliu ever solved that problem...

**Comment by metaclips** [comment]
> i am getting a simliar error when building libmdns but not with this library,
> 
> the error appears also if you were only building libmdns on illumos...
> 
> 
> 
> i was just curious if rainliu ever solved that problem...

Not all OSs support reuse_port/SO_REUSEPORT mostly, reuse_address is sufficient eg [windows](https://docs.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse).
